USE [master]
GO
/****** Object:  Database [AssetDB]    Script Date: 4/7/2021 9:37:27 PM ******/
CREATE DATABASE [AssetDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AssetDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AssetDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AssetDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AssetDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AssetDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AssetDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AssetDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AssetDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AssetDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AssetDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AssetDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [AssetDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AssetDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AssetDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AssetDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AssetDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AssetDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AssetDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AssetDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AssetDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AssetDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AssetDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AssetDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AssetDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AssetDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AssetDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AssetDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AssetDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AssetDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AssetDB] SET  MULTI_USER 
GO
ALTER DATABASE [AssetDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AssetDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AssetDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AssetDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AssetDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AssetDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [AssetDB] SET QUERY_STORE = OFF
GO
USE [AssetDB]
GO
/****** Object:  Table [dbo].[Assets]    Script Date: 4/7/2021 9:37:27 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Assets](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[AssetName] [varchar](200) NULL,
	[CountryOfDepartment] [varchar](200) NULL,
	[EMailAdressOfDepartment] [varchar](200) NULL,
	[PurchaseDate] [date] NULL,
	[Broken] [bit] NULL,
	[Department] [int] NULL,
 CONSTRAINT [PK__Asset__3213E83FC073A0ED] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [AssetDB] SET  READ_WRITE 
GO
